name: hidro
description: "Hidro - Temporizador de jejum e rastreador de água"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  flutter_local_notifications: 19.4.1
  timezone: ^0.10.0
  fl_chart: ^0.71.0
  share_plus: ^10.1.4
  file_picker: ^8.1.7
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
